apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
  - name: nginx
    image: bitnami/nginx
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
      capabilities:
        drop: ["ALL"]
      seccompProfile: 
        type: RuntimeDefault
    volumeMounts:
    - name: configmap-volume
      mountPath: /app
  volumes:
  - name: configmap-volume
    configMap:
      name: configmap-01
