#Write a pod manifest that contains a volume:
#
#pod settings:
#name: alpine02
#containers: a single container, based on the alpine image
#volume settings:
#name: empty-volume
#type: emptyDir
#mounted in the container under /scratch
apiVersion: v1
kind: Pod
metadata:
  name: alpine02
spec:
  containers:
    - image: alpine
      name: alpine
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /scratch
          name: empty-volume
  volumes:
    - name: empty-volume
      emptyDir: {}
